workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_OPEN_MERGE_REQUESTS
      when: never
    - when: always

.python_template:
  image: python:3.9
  interruptible: true
  needs: [ ]
  before_script:
    - python -m venv venv
    - . ./venv/bin/activate
    - pip install --upgrade "pip<23.1.0"
    - pip install -r dev.requirements.txt -U --upgrade-strategy=eager
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  tags:
    - docker

test_python:
  extends: .python_template
  stage: test
  script:
    - coverage run -m pytest --junitxml=report.xml ./tests
    - coverage xml -o coverage.xml
    - coverage report -m --skip-covered
  coverage: '/\d+\%\s*$/'
  artifacts:
    paths:
      - ".coverage"
    expire_in: 1 hour
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

lint_python:
  extends: .python_template
  stage: test
  script:
    - black . --check -l 120 --exclude=venv

publish_python:
  extends: .python_template
  stage: publish
  script:
    - echo "$CI_COMMIT_TAG" > VERSION
    - pip install build
    - python -m build -s -w --no-isolation
    - twine upload dist/envify-${CI_COMMIT_TAG/-/\+}*
  rules:
    - if: $CI_COMMIT_TAG

stages:
  - test
  - publish